server:
  port: 18060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    department:
      path: /department/**
      serviceId: departmentservice
    employee:
      path: /employee/**
      serviceId: employeeservice
    organization:
      path: /organization/**
      serviceId: organizationservice